### ISSUE TITLE
Problem with cache: The payload is invalid

### ISSUE THREAD

**Issue by Reefki** [Intervention/image#427]
I have a problem with image cache, I'm using Laravel 5.1 and database cache driver.

```
DecryptException in BaseEncrypter.php line 45:
The payload is invalid.
```

Here is the code of my controller
```
$img = Image::cache(function($image) use ($path) {
    return $image->make($path);
}, 10, true);

return $img->response();
```

First time visit was good, it occurs when I reload the browser.

Edit: I have two images for test 7kb & 32kb PNG file, the problem is only on the 32kb file.

**Comment by olivervogel** [comment]
`BaseEncrypter.php` is not part of Intervention Image or Imagecache. Maybe this is another libraries problem?

**Comment by Reefki** [comment]
@olivervogel thanks for your reply

Yes `BaseEncrypter.php` is not part of image or image cache, it was Laravel's encryption.

Here is the full stack trace of the error:

```
[2015-09-22 11:33:06] local.ERROR: exception 'Illuminate\Contracts\Encryption\DecryptException' with message 'The payload is invalid.' in /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Encryption/BaseEncrypter.php:45

Stack trace:
#0 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(85): Illuminate\Encryption\BaseEncrypter->getJsonPayload('eyJpdiI6IlRnaFN...')
#1 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(84): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6IlRnaFN...')
#2 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\Cache\DatabaseStore->get('1fec428d10d0f05...')
#3 [internal function]: Illuminate\Cache\Repository->get('1fec428d10d0f05...')
#4 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(310): call_user_func_array(Array, Array)
#5 /Users/Reefki/sites/project/vendor/intervention/imagecache/src/Intervention/Image/ImageCache.php(298): Illuminate\Cache\CacheManager->__call('get', Array)
#6 /Users/Reefki/sites/project/vendor/intervention/imagecache/src/Intervention/Image/ImageCache.php(298): Illuminate\Cache\CacheManager->get('1fec428d10d0f05...')
#7 /Users/Reefki/sites/project/vendor/intervention/image/src/Intervention/Image/ImageManager.php(88): Intervention\Image\ImageCache->get(10, true)
#8 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Intervention\Image\ImageManager->cache(Object(Closure), 10, true)
#9 /Users/Reefki/sites/project/app/Http/Controllers/FileController.php(70): Illuminate\Support\Facades\Facade::__callStatic('cache', Array)
#10 /Users/Reefki/sites/project/app/Http/Controllers/FileController.php(70): Intervention\Image\Facades\Image::cache(Object(Closure), 10, true)
#11 [internal function]: App\Http\Controllers\FileController->show(Object(Illuminate\Http\Request), Object(App\File))
#12 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#13 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('show', Array)
#14 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\FileController), Object(Illuminate\Routing\Route), 'show')
#15 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\FileController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'show')
#21 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'show')
#22 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#23 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#37 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /Users/Reefki/sites/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /Users/Reefki/sites/project/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}
```

**Comment by Reefki** [comment]
I also tried using imagecache routes, `small` and `medium` template was good, but `large` template return the same error.

**Comment by olivervogel** [comment]
Sorry, this seems to be a local issue. Can't help here.

**Comment by Reefki** [comment]
Ok thanks, I end up with using cache file storage only for image caching since laravel allowed to use multiple cache storage like so:

```
if ( Cache::store('file')->has($key) ) {
    $img = Cache::store('file')->get($key);
    $image = Image::make($img);
    $cachedImage = new \Intervention\Image\CachedImage;
    return $cachedImage->setFromOriginal($image, $key)->response();
}

$img = Image::make($path);
$encoded = $img->encoded ? $img->encoded : (string) $img->encode();
Cache::store('file')->put($file->name, $encoded, 10);
return $img->response('png');
```

Its worked! It seems this problem only occurs when using database driver, I do cache another serialized object on database storage but never facing this issue, I doubt it was a local issue.

It would be great if you add cache storage option on the imagecache config file.

Thank you

**Comment by v920749** [comment]
You can just add this 'options'   => [
                PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216
            ]  to 'mysql' => [
			'driver'    => 'mysql',
			'host'      => env('DB_HOST', 'localhost'),
			'database'  => env('DB_DATABASE', 'forge'),
			'username'  => env('DB_USERNAME', 'forge'),
			'password'  => env('DB_PASSWORD', ''),
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
            'options'   => [
                PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216
            ]

**Comment by v920749** [comment]
Dont forget to make the "value" column as longtext in cache table plus this addition config in database.php 'options' => [
PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216
]

**Comment by ijin82** [comment]
@v920749 thanks, that's fix for problem. So just create your cache table like this:
```php
Schema::create('cache', function($table) {
            $table->string('key')->unique();
            $table->mediumText('value');
            $table->integer('expiration');
        });
```

**Comment by tremby** [comment]
I just hit the same problem in a totally unrelated context. Same thing -- laravel cache value database column was too narrow.

**Comment by vluzrmos** [comment]
You just have to change the column value to a longer type, like longtext.

**Comment by Lychee555** [comment]
'options' => [
PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216
]
Somebody who knows the result? Please tell me ,there is some amazing phenomenon...
